### ISSUE TITLE
Does the champion have to be a member of TC39?

### ISSUE THREAD

**Issue by rauschma** [tc39/process-document#4]
In stage 1, the following is an entrance criterion: ‘Identified “champion” who will advance the addition’.

Suggestion: state explicitly whether the champion must be a member of TC39.

**Comment by mathiasbynens** [comment]
How do you define “TC39 member’?

[Ecma members](https://www.ecma-international.org/memento/members.htm) are companies, not individuals.

AFAIK a champion is simply the person who presents a proposal at a TC39 meeting. It doesn’t matter if they work for an Ecma member company or if they got invited to the meeting by a member organization some other way.

**Comment by ljharb** [comment]
There must always be a TC39 member (which technically means a delegate representing a member company) who is the champion; others can co-champion if the member champion is willing.

**Comment by mathiasbynens** [comment]
> others can co-champion if the member champion is willing.

What do you mean by “others” here? Isn’t everyone attending a TC39 meeting representing an Ecma member in one way or another?

**Comment by ljharb** [comment]
Invited guests can't be champions by themselves.

**Comment by chicoxyzzy** [comment]
I have heard different points of view on whether an invited expert can be a champion or not. Although such cases were happen before, some delegates said that it's not possible. I think we need to get consensus on this and add clarification to docs.

**Comment by ljharb** [comment]
@chicoxyzzy invited *guests* can not; invited experts have been champions many times. The difference to me (one that's not codified, to be fair) is that invited guests just show up for a meeting or two, because a delegate invited them with the ecma chair's permission; an invited expert is someone that the TC39 committee invites to attend regularly due to their expertise on various topics.

I agree we should clarify things here.

**Comment by littledan** [comment]
Right, I agree we should clarify things. I don't believe we have an "invited guest" policy, though that term is in use. We have invited experts in TC39, as permitted by the Ecma rules and bylaws. Everyone who attends a TC39 meeting must generally be a member or invited expert; we also permit propective members or observers under certain circumstances. Observers can't contribute to the committee, so they can't champion proposals. Sometimes, invited experts are referred to as invited guests, but I don't believe there's any difference in policy. The invited expert policy used to be more informal, and we're in the process of formalizing it more. I agree that invited experts should be able to champion proposals.

**Comment by ljharb** [comment]
@littledan when I first attended TC39 in 2014, I was told that any delegate could invite a guest with the chair's permission, per Ecma rules, and they were allowed to only attend twice ever as a guest - that's the Ecma policy I'm referring to.

Invited experts are as you describe.

**Comment by littledan** [comment]
I don't dispute that people have said various versions of those things. I don't want to further characterize the policy or history on this thread, for fear of introducing further ambiguity. The chair group has previously said that they will document the invited expert policy in more detail.

**Comment by gesa** [comment]
oh my god y'all i have written and re-written my response so many times bc I keep getting off track from the original question bc international bureaucracy is haaaaard.

Okay here we go. Based on my interpretation of Ecma policy, which, **IANAL**, Invited Experts can champion proposals. It makes sense, too, because frequently individuals are invited by the SG as Invited Experts for the purpose of continuity of work while between employers or moving to a non-member employer. See [article 6.2.6](https://www.ecma-international.org/memento/EcmaRules.htm#art6.2.6) of the Ecma Rules.

We also have additional internal documents intended to clarify what is expected of individuals invited as Ecma Fellows, Observers, Liaisons, Perspective Members, etc etc etc. Generally: they cannot champion a proposal.

**Comment by ctcpip** [comment]
Closing, as this should be clear at this point and the relevant docs in `how-we-work` reflect this.
